# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Fri Nov 16 16:46:14 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(994, 595)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet(_fromUtf8("QGroupBox { \n"
"     border: 1px solid gray; \n"
"     border-radius: 5px; \n"
" } \n"
"\n"
"QGroupBox::title { \n"
"     background-color: transparent;\n"
"     subcontrol-position: top left; /* position at the top left*/ \n"
"     padding:3 8px;\n"
" } "))
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.optionsPage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optionsPage.sizePolicy().hasHeightForWidth())
        self.optionsPage.setSizePolicy(sizePolicy)
        self.optionsPage.setObjectName(_fromUtf8("optionsPage"))
        self.gridLayout = QtGui.QGridLayout(self.optionsPage)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.optionsLayout = QtGui.QVBoxLayout()
        self.optionsLayout.setObjectName(_fromUtf8("optionsLayout"))
        self.filePathLayout = QtGui.QHBoxLayout()
        self.filePathLayout.setObjectName(_fromUtf8("filePathLayout"))
        self.filePath = QtGui.QLineEdit(self.optionsPage)
        self.filePath.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.filePath.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.filePath.setToolTip(_fromUtf8(""))
        self.filePath.setStatusTip(_fromUtf8(""))
        self.filePath.setWhatsThis(_fromUtf8(""))
        self.filePath.setReadOnly(False)
        self.filePath.setObjectName(_fromUtf8("filePath"))
        self.filePathLayout.addWidget(self.filePath)
        self.browseButton = QtGui.QPushButton(self.optionsPage)
        self.browseButton.setDefault(False)
        self.browseButton.setObjectName(_fromUtf8("browseButton"))
        self.filePathLayout.addWidget(self.browseButton)
        self.optionsLayout.addLayout(self.filePathLayout)
        self.parametersLayout = QtGui.QHBoxLayout()
        self.parametersLayout.setObjectName(_fromUtf8("parametersLayout"))
        spacerItem = QtGui.QSpacerItem(0, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.parametersLayout.addItem(spacerItem)
        self.groupBox = QtGui.QGroupBox(self.optionsPage)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setContentsMargins(-1, 20, -1, -1)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.segmentButton = QtGui.QPushButton(self.groupBox)
        self.segmentButton.setEnabled(True)
        self.segmentButton.setObjectName(_fromUtf8("segmentButton"))
        self.gridLayout_5.addWidget(self.segmentButton, 9, 0, 1, 1)
        self.segProgress = QtGui.QProgressBar(self.groupBox)
        self.segProgress.setMaximum(100)
        self.segProgress.setProperty("value", 0)
        self.segProgress.setObjectName(_fromUtf8("segProgress"))
        self.gridLayout_5.addWidget(self.segProgress, 10, 0, 1, 2)
        self.everySecondOption = QtGui.QRadioButton(self.groupBox)
        self.everySecondOption.setObjectName(_fromUtf8("everySecondOption"))
        self.gridLayout_5.addWidget(self.everySecondOption, 2, 0, 1, 2)
        self.startFrame = QtGui.QLineEdit(self.groupBox)
        self.startFrame.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.startFrame.setObjectName(_fromUtf8("startFrame"))
        self.gridLayout_5.addWidget(self.startFrame, 5, 0, 1, 1)
        self.lastFrameButton = QtGui.QPushButton(self.groupBox)
        self.lastFrameButton.setEnabled(False)
        self.lastFrameButton.setCheckable(False)
        self.lastFrameButton.setObjectName(_fromUtf8("lastFrameButton"))
        self.gridLayout_5.addWidget(self.lastFrameButton, 7, 1, 1, 1)
        self.highlightFacesOption = QtGui.QCheckBox(self.groupBox)
        self.highlightFacesOption.setObjectName(_fromUtf8("highlightFacesOption"))
        self.gridLayout_5.addWidget(self.highlightFacesOption, 8, 0, 1, 2)
        self.barState = QtGui.QLabel(self.groupBox)
        self.barState.setText(_fromUtf8(""))
        self.barState.setObjectName(_fromUtf8("barState"))
        self.gridLayout_5.addWidget(self.barState, 11, 0, 1, 2)
        self.everyTwoSecondsOption = QtGui.QRadioButton(self.groupBox)
        self.everyTwoSecondsOption.setChecked(True)
        self.everyTwoSecondsOption.setObjectName(_fromUtf8("everyTwoSecondsOption"))
        self.gridLayout_5.addWidget(self.everyTwoSecondsOption, 3, 0, 1, 2)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 4, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.blackFramesOption = QtGui.QRadioButton(self.groupBox)
        self.blackFramesOption.setObjectName(_fromUtf8("blackFramesOption"))
        self.gridLayout_5.addWidget(self.blackFramesOption, 1, 0, 1, 2)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 6, 0, 1, 1)
        self.endFrame = QtGui.QLineEdit(self.groupBox)
        self.endFrame.setObjectName(_fromUtf8("endFrame"))
        self.gridLayout_5.addWidget(self.endFrame, 7, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 12, 0, 1, 2)
        self.parametersLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.optionsPage)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setContentsMargins(-1, 20, -1, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.videoTitleLabel = QtGui.QLabel(self.groupBox_2)
        self.videoTitleLabel.setEnabled(True)
        self.videoTitleLabel.setObjectName(_fromUtf8("videoTitleLabel"))
        self.verticalLayout_2.addWidget(self.videoTitleLabel)
        self.videoLengthLabel = QtGui.QLabel(self.groupBox_2)
        self.videoLengthLabel.setObjectName(_fromUtf8("videoLengthLabel"))
        self.verticalLayout_2.addWidget(self.videoLengthLabel)
        spacerItem2 = QtGui.QSpacerItem(180, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.parametersLayout.addWidget(self.groupBox_2)
        self.optionsLayout.addLayout(self.parametersLayout)
        self.gridLayout.addLayout(self.optionsLayout, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.optionsPage)
        self.videoPage = QtGui.QWidget()
        self.videoPage.setObjectName(_fromUtf8("videoPage"))
        self.gridLayout_3 = QtGui.QGridLayout(self.videoPage)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.videoLayout = QtGui.QVBoxLayout()
        self.videoLayout.setObjectName(_fromUtf8("videoLayout"))
        self.menuLayout = QtGui.QHBoxLayout()
        self.menuLayout.setObjectName(_fromUtf8("menuLayout"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.menuLayout.addItem(spacerItem3)
        self.newButton = QtGui.QPushButton(self.videoPage)
        self.newButton.setObjectName(_fromUtf8("newButton"))
        self.menuLayout.addWidget(self.newButton)
        self.saveButton = QtGui.QPushButton(self.videoPage)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.menuLayout.addWidget(self.saveButton)
        self.videoLayout.addLayout(self.menuLayout)
        self.previewLayout = QtGui.QHBoxLayout()
        self.previewLayout.setObjectName(_fromUtf8("previewLayout"))
        self.segmentList = QtGui.QListView(self.videoPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.segmentList.sizePolicy().hasHeightForWidth())
        self.segmentList.setSizePolicy(sizePolicy)
        self.segmentList.setObjectName(_fromUtf8("segmentList"))
        self.previewLayout.addWidget(self.segmentList)
        self.videoBackground = QtGui.QGroupBox(self.videoPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoBackground.sizePolicy().hasHeightForWidth())
        self.videoBackground.setSizePolicy(sizePolicy)
        self.videoBackground.setMinimumSize(QtCore.QSize(0, 0))
        self.videoBackground.setAutoFillBackground(False)
        self.videoBackground.setStyleSheet(_fromUtf8("QGroupBox#videoBackground { \n"
"     background: black;\n"
" } "))
        self.videoBackground.setTitle(_fromUtf8(""))
        self.videoBackground.setObjectName(_fromUtf8("videoBackground"))
        self.gridLayout_4 = QtGui.QGridLayout(self.videoBackground)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.videoPlayer = phonon.Phonon.VideoPlayer(self.videoBackground)
        self.videoPlayer.setMinimumSize(QtCore.QSize(0, 0))
        self.videoPlayer.setObjectName(_fromUtf8("videoPlayer"))
        self.gridLayout_4.addWidget(self.videoPlayer, 0, 0, 1, 1)
        self.previewLayout.addWidget(self.videoBackground)
        self.videoLayout.addLayout(self.previewLayout)
        self.controlsLayout = QtGui.QHBoxLayout()
        self.controlsLayout.setObjectName(_fromUtf8("controlsLayout"))
        self.previousButton = QtGui.QPushButton(self.videoPage)
        self.previousButton.setEnabled(False)
        self.previousButton.setObjectName(_fromUtf8("previousButton"))
        self.controlsLayout.addWidget(self.previousButton)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.controlsLayout.addItem(spacerItem4)
        self.playButton = QtGui.QPushButton(self.videoPage)
        self.playButton.setEnabled(False)
        self.playButton.setObjectName(_fromUtf8("playButton"))
        self.controlsLayout.addWidget(self.playButton)
        self.playNextButton = QtGui.QPushButton(self.videoPage)
        self.playNextButton.setEnabled(False)
        self.playNextButton.setObjectName(_fromUtf8("playNextButton"))
        self.controlsLayout.addWidget(self.playNextButton)
        self.pauseButton = QtGui.QPushButton(self.videoPage)
        self.pauseButton.setEnabled(False)
        self.pauseButton.setObjectName(_fromUtf8("pauseButton"))
        self.controlsLayout.addWidget(self.pauseButton)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.controlsLayout.addItem(spacerItem5)
        self.nextButton = QtGui.QPushButton(self.videoPage)
        self.nextButton.setEnabled(False)
        self.nextButton.setObjectName(_fromUtf8("nextButton"))
        self.controlsLayout.addWidget(self.nextButton)
        self.videoLayout.addLayout(self.controlsLayout)
        self.gridLayout_3.addLayout(self.videoLayout, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.videoPage)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Video Segmentation", None, QtGui.QApplication.UnicodeUTF8))
        self.filePath.setText(QtGui.QApplication.translate("MainWindow", "/homes/jp2310/Documents/3rd year/Project/icl_video_segmentation/res/skyfall.mp4", None, QtGui.QApplication.UnicodeUTF8))
        self.filePath.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Please load a video file.", None, QtGui.QApplication.UnicodeUTF8))
        self.browseButton.setText(QtGui.QApplication.translate("MainWindow", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.segmentButton.setText(QtGui.QApplication.translate("MainWindow", "Segment", None, QtGui.QApplication.UnicodeUTF8))
        self.everySecondOption.setText(QtGui.QApplication.translate("MainWindow", "Every second", None, QtGui.QApplication.UnicodeUTF8))
        self.startFrame.setText(QtGui.QApplication.translate("MainWindow", "200", None, QtGui.QApplication.UnicodeUTF8))
        self.lastFrameButton.setText(QtGui.QApplication.translate("MainWindow", "Last frame", None, QtGui.QApplication.UnicodeUTF8))
        self.highlightFacesOption.setText(QtGui.QApplication.translate("MainWindow", "Highlight faces", None, QtGui.QApplication.UnicodeUTF8))
        self.everyTwoSecondsOption.setText(QtGui.QApplication.translate("MainWindow", "Every two seconds", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Start frame : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Split type", None, QtGui.QApplication.UnicodeUTF8))
        self.blackFramesOption.setText(QtGui.QApplication.translate("MainWindow", "On black frames", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "End frame : ", None, QtGui.QApplication.UnicodeUTF8))
        self.endFrame.setText(QtGui.QApplication.translate("MainWindow", "400", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.videoTitleLabel.setText(QtGui.QApplication.translate("MainWindow", "Title:", None, QtGui.QApplication.UnicodeUTF8))
        self.videoLengthLabel.setText(QtGui.QApplication.translate("MainWindow", "Video length: ", None, QtGui.QApplication.UnicodeUTF8))
        self.newButton.setText(QtGui.QApplication.translate("MainWindow", "New segmentation", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.previousButton.setText(QtGui.QApplication.translate("MainWindow", "Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.playButton.setText(QtGui.QApplication.translate("MainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.playNextButton.setText(QtGui.QApplication.translate("MainWindow", "Play next", None, QtGui.QApplication.UnicodeUTF8))
        self.pauseButton.setText(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.nextButton.setText(QtGui.QApplication.translate("MainWindow", "Next", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import phonon
